### ISSUE TITLE
User friendly error message

### ISSUE THREAD

**Issue by jalakoo** [acrocat/EverLayoutBridge#1]
Hey, thanks for building this.  Minor thing, but first time I ran the bridge port 3000 was in use, so I experienced the following console output:

```Listening on port 3000
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at Server.listen (net.js:1466:7)
    at Object.createServer (/usr/local/lib/node_modules/ever-layout-bridge/lib/network.js:26:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/ever-layout-bridge/lib/ever-layout-bridge.js:66:9)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)```

Fairly clear from the stack track but a friendly one-line message error (or auto alternate port selection) would be solid.

**Comment by Stitarmare** [comment]
Same issue what should we do!

**Comment by acrocat** [comment]
@Stitarmare The issue being reported is just that the error message is ugly. I'm embarrassed to admit that I still haven't looked into this... but I will! If you're seeing this error though you can resolve it by hosting on a different port:

`ever-layout-bridge --port=3333`
